services:
  windows:
    image: windows-local
    container_name: windows
    environment:
      VERSION: "win11e"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ./custom.iso:/custom.iso
